happo/happo.io

- README.md
Just correcting where to require RemoteBrowserTarget from.
> Require happo.io instead of happo in the docs

- package.json
- src/processSnapsInBundle.js
- src/reactDOMRunner.js
Since we render components in a jsdom environment, then send the payload
(html + css) to happo.io, we've basically executed javascript in a 0x0
sized window. Any code relying on window dimensions would have had to
work with that limitation. This isn't ideal, and we can quite easily fix
it by overriding dimensions with the ones we have specified in the
.happo.js config.
The downside with this approach is that we have to render all components
multiple times. One for each target. The upside is that any code relying
on window dimensions (innerWidth, outerWidth, screen.width, etc) will
generate the right markup.
> Window dimensions

- package.json
- yarn.lock
In a package where we use Happo, running `yarn` I saw the following warning:
> warning " > babel-loader@7.1.4" has unmet peer dependency "babel-core@6".
When running `yarn` in happo.io while investigating the above, I
saw the warnings:
> warning " > babel-loader@7.1.4" has unmet peer dependency "babel-core@6".
> warning " > babel-jest@22.4.3" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".
This commit addresses the warnings by adding `babel-core` as a dependency.
I had considered making it a peer-dependency, but considering the amount of `babel-*` things in this repo, it seems nicer for end users to just add it here so they don't need to deal with it.
> Add babel-core as a dependency

- .eslintrc.js
- package.json
- src/Logger.js
- src/MultipleErrors.js
- src/RemoteBrowserTarget.js
- src/WrappedError.js
- src/cli.js
- src/commands/dev.js
- src/commands/run.js
- src/createDynamicEntryPoint.js
- src/createWebpackBundle.js
- src/domRunner.js
- src/executeCli.js
- src/getComponentNameFromFileName.js
- src/processSnapsInBundle.js
- yarn.lock
Instead of automatically trying to generate screenshots every time the
user saves a file, we now wait for a keypress before we continue. This
is better because it allows you to work on the file for a while before
committing to generate the screenshots. Often times, there will be build
failures before you can continue anyway.
> Wait for keypress on dev change detected

- bin/happo-ci
- package.json
- src/executeCli.js
- src/loadUserConfig.js
- src/processSnapsInBundle.js
- test/integrations/examples/Bar-react-happo.js
- test/integrations/react-test.js
- test/loadUserConfig-test.js
Providing secret environment variables in CI to forks is tricky. Most CI
environments, such as Travis, explicitly disable secrets when it detects
that a run is triggered on a fork of a repo.
https://github.com/travis-ci/travis-ci/issues/1946
To work around this, I've adopted a separate auth mechanism for happo.io
for outside pull requests. Instead of requiring an apiKey and an
apiSecret, we use temporary tokens, pulled from the Happo API if we
detect that we're in a fork (keys are missing). These tokens are much
more limited in scope compared to the regular API tokens. We're
basically allowing them to generate reports for the PR in question, and
only for a limited time.
> Use temporary pull-request token for PRs from forks

- src/loadUserConfig.js
This should make it easier to debug when apiKey and apiSecret isn't
provided.
> Add a log when fallback auth is used

- README.md
- src/domRunner.js
- src/processSnapsInBundle.js
Allows users to override their `JSDOM` constructor options
in case they need to so something special with their window
runner.
In particular this is useful for getting around a security issue
from `jsdom` that expects users to define a domain to run on
when accessing `localStorage`.
I need advice on how to test this better and am open for
other suggestions.
> Add `jsdomOptions` as allowed parameter to `.happo.js`

- package.json
- src/inlineResources.js
- test/inlineResources-test.js
- yarn.lock
Up until now, we've only been inlining images found in the `src`
attribute of an image. By also including `srcset` we can prevent
examples with broken images.
I found this while working on a PR to add Happo testing to Gatsby.
https://github.com/trotzig/gatsby/commit/86b177bd020e713662540a8c38b51ab69dc504f2
> Inline images in srcset attributes

- bin/happo-ci
A customer reported that the happo-ci script failed intermittently due
to package-lock.json being modified as part of the `npm install`.
error: Your local changes to the following files would be overwritten by checkout:
package-lock.json
Please, commit your changes or stash them before you can switch branches.
Yarn has a --pure-lockfile flag to prevent yarn.lock from being touched.
https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-pure-lockfile
Finding a flag for npm was trickier. I think the real fix is to use `npm
ci`, https://docs.npmjs.com/cli/ci. But I don't want to introduce that
change right now as I know too little of the side-effects. Instead, the
--no-save flag seems to do the trick, as verified locally and in this
npm issue:
https://github.com/npm/npm/issues/17761
> Avoid touching lockfiles when installing dependencies

- src/getComponentNameFromFileName.js
- test/getComponentNameFromFileName-test.js
I noticed a project with very long component names. I hadn't properly
taken typescript into account.
> Improve getComponentFromFilename for /\.tsx?/ files

- .babelrc
- .eslintrc.js
- LICENSE
- README.md
- package.json
- src/createWebpackBundle.js
- src/loadUserConfig.js
- test/integrations/examples/Foo-react-happo.js
- test/integrations/examples/dynamically-imported.js
- test/integrations/react-test.js
- yarn.lock
By default, [webpack will treat a dynamic import as a split point](https://webpack.js.org/api/module-methods/#import-),
meaning it will try to download a bundle as part of evaluating an
`import(somePath)` statement. This won't work for Happo -- since there's
no running server, people end up with something like this:
```
Error: Could not load script: "http://localhost/92.happo-bundle-react-L3Jvb3Qvc3R1ZGlv.js"
at onErrorWrapped (/root/studio/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:39:19)
at Object.check (/root/studio/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:58:23)
at request.then.catch.err (/root/studio/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:104:14)
```
To work around this, I'm using the …
> Dynamic import

- README.md
- src/DEFAULTS.js
- src/createDynamicEntryPoint.js
- src/domRunner.js
- src/renderWrapper.js
- test/integrations/examples/Foo-react-happo.js
- test/integrations/react-test.js
- test/integrations/renderWrapper.js
- test/integrations/theme.js
A lot of projects using Happo end up relying on wrapper components
automatically injecting things like theme properties, store bindings etc
through React contexts. To avoid having to specify these wrappers every
single time, I'm adding a `renderWrapperModule` config option. With this
option, they can implement a custom wrapping function for all Happo
examples, something like
```js
// .happo.js
renderWrapperModule: path.resolve(__dirname, 'happo-wrapper.js');
```
```js
// happo-wrapper.js
export default (component) => (
<ThemeProvider>{component}</ThemeProvider>
);
```
Fixes #25
> Allow custom render wrappers

- src/DEFAULTS.js
- src/createWebpackBundle.js
This will make it easier to use happo in typescript projects, since you
no longer have to override things, e.g.
customizeWebpackConfig: config => {
config.resolve = Object.assign({}, config.resolve, {
extensions: ['.tsx', '.ts', '.js'],
}); // add in the existing config.resolve that happo needs
return config;
}
include: '**/@(*-happo|happo).@(ts|tsx)',
While this is very specific to typescript, it shouldn't hurt regular
projects.
> Include typescript files when searching by extension

- src/domRunner.js
- test/integrations/react-test.js
I'm working on the happo-plugin-scrape plugin where I'm running into
performance issues related to css handling. The slow part is injecting a
large block of css collected in the scrape phase to the JSDOM instance.
Instead of doing that, we can allow the plugin to directly inject css,
avoiding the need to pass this css through the JSDOM instance.
> Allow plugins to inject css outside of rendering examples

- package.json
Hi :wave:,
I am working on upgrading a project to babel 7 and noticed a console warning from happo after an npm install.
```sh
npm WARN happo.io@3.3.0 requires a peer of babel-core@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
```
I do actually have babel-core installed, but it is `7.0.0-bridge.0` as necessitated by jest, as described here --> https://jestjs.io/docs/en/getting-started.html#using-babel.
This PR simply loosens up the versioning a tad to allow for the `-bridge.0` portion.
> Allow for more flexible babel-core peer dependency version

- package.json
- src/RemoteBrowserTarget.js
- src/commands/run.js
- src/remoteRunner.js
- test/integrations/MockTarget.js
- test/integrations/static-test.js
I'm working on improvements to the happo-plugin-storybook plugin. As
part of that, I'm making plugins able to bypass local DOM rendering and
instead send a full static build to happo.io for remote execution.
> Add support for static builds from plugins

- src/prepareAssetsPackage.js
- test/prepareAssetsPackage-test.js
I noticed that payload caching isn't working well with the latest
version of the happo.io client. This is because `archiver` is making
different zip packages every time. By locking the creation date to a
specific time we can have consistent packages created.
> Create consistent zip packages

- src/RemoteBrowserTarget.js
- test/RemoteBrowserTarget-test.js
I introduced a bug in 3.9.0 causing the happo-plugin-storybook to fail.
In some cases, snapPayloads will be empty (as in
happo-plugin-storybook). We can handle this by shortcutting `chunks`.
Fixes #58
> Fix running happo for happo-plugin-storybook

- src/RemoteBrowserTarget.js
- src/commands/compareReports.js
- src/makeRequest.js
- src/uploadReport.js
- test/makeRequest-test.js
After getting feedback that happo runs are flaky in CI, I decided to add
some retry-logic to the requests made from the client. The new logic
will make requests retry up to three times with a two second delay
before giving up.
> Retry requests

- package.json
- src/RemoteBrowserTarget.js
- src/constructReport.js
- test/RemoteBrowserTarget-test.js
This will allow the happo.io server to better associate sources with a
snapshot.
> Pass along snapRequestId with snapshot

- src/RemoteBrowserTarget.js
- test/RemoteBrowserTarget-test.js
I was suspecting a bug, off-by-one in the chunking mechanism in
RemoteBrowserTarget. But it doesn't look like I can provoke it.
> Add tests to verify chunks for large test suites

- package.json
- src/RemoteBrowserTarget.js
- test/RemoteBrowserTarget-test.js
This will make it possible to split up happo runs involving the
happo-plugin-storybook plugin into multiple parallel ones.
The happo workers have already been updated to support the new chunks feature.
> Add support for chunks when using staticPackage

- src/browser/getRenderFunc.js
- src/browser/processor.js
- src/browser/validateAndFilterExamples.js
- test/integrations/error-test.js
- test/integrations/examples/Foo-error-misconfigured-happo.js
- test/integrations/examples/Generated-react-happo.js
- test/integrations/react-test.js
This commit fixes a confusing bug that had different symptoms in
different DOM providers. Basically, a happo file that looked like this:
export const foo = () => <div>Hello</div>;
export const bar = <div>Hello</div>;
- would not render any examples in puppeteer
- would silently ignore `bar` in jsdom
The silent failure in puppeteer was because we were trying to serialize
something that wasn't serializable. And then puppeteer silently returns
undefined. This bug:
https://github.com/GoogleChrome/puppeteer/issues/242
The ignore in jsdom was because we had code in place to ignore
render-less exports (some build tools add these).
The fix is to yell loudly as soon as we come across an example that's
misconfigured. I did change the example ignore logic a little, now
there's an assumption that any …
> Don't silently fail when example has no render method

- .eslintrc.js
- bin/happo-ci
- package.json
- src/Logger.js
- src/commands/startJob.js
- src/executeCli.js
This command will tell happo.io about what to expect from the current ci
run. So far, it is best suited for a multi-project setups, where you
want to combine multiple happo runs in a single status.
> Add `happo start-job` command, use it in happo-ci

- .eslintrc.js
- README.md
- package.json
- src/DEFAULTS.js
- src/browser/processor.js
- src/browser/remoteRenderer.js
- src/browser/validateAndFilterExamples.js
- src/createDynamicEntryPoint.js
- src/createStaticPackage.js
- src/debug.html
- src/domRunner.js
- src/executeCli.js
- src/postGithubComment.js
- src/processSnapsInBundle.js
- test/integrations/react-test.js
- test/postGithubComment-test.js
By default, examples are pre-rendered in jsdom (or puppeteer when the
happo-plugin-puppeteer plugin is used). There are a few reasons we do
this:
- easier to surface errors to the user
- slightly better performance (although it was a long time since I
measured)
- no javascript code is shipped over the wire (instead, only html+css)
In the majority of cases, this approach is just fine. But recently I've
started coming across more and more cases where pre-rendering is making
things difficult. For custom web elements using the shadow dom,
pre-rendering is pretty much not working. To mitigate that, I'm
introducing a `prerender` configuration option. The default will be
`true`. By setting it to false, you leave rendering up to the happo.io
workers.
Also in this PR: a way to get happo statuses …
> Add support for remote rendering + an alternative way of posting statuses

- package.json
- src/commands/debug.js
- yarn.lock
A dependency of http-server was removed from npm. As a result, all
http-server installations currently fail. While we wait for a fix, we
can temporarily remove our usage of http-server. Only the `happo debug`
command is affected, which I think is okay.
Fixes #73
See https://github.com/indexzero/http-server/issues/521 for context.
> Temporarily remove usage of http-server

- .happo.js
- package.json
- src/RemoteBrowserTarget.js
- yarn.lock
The default cutoff point on happo workers is 5000px. Any example larger
than that will be cropped. Now that we have full-page support, this
number is starting to feel a little small. But instead of globally
bumping it I'm making a change to RemoteBrowserTarget that will allow
you to set a custom maxHeight.
> Allow setting `maxHeight` for browser target

- README.md
- bin/happo-ci-circleci
Up until now all projects have been using origin/master as the base
branch. In the Rocket.Chat repository however, the base branch is
`develop`. By allowing people to override the default origin/master
through an environment variable, we support projects like these as well.
https://github.com/RocketChat/Rocket.Chat/branches
Fixes #79
> Allow different base branch than master in CircleCI

- README.md
- src/loadUserConfig.js
- test/.happo-alternate.js
- test/loadUserConfig-test.js
We already have the `--config` option for the CLI tool, but that doesn't
work in the ci scripts. To allow a config override to pierce through to
the different `happo` ci invocations, I'm adding support for an env
variable.
> Allow HAPPO_CONFIG_FILE env variable to specify path to config

- .babelrc
- package.json
- src/loadUserConfig.js
- test/.happo-alternate-async.js
- test/loadUserConfig-test.js
- yarn.lock
This PR changes how the `.happo.js` config file is loaded. It allows asynchronous execution within the config file itself to do things such as spinning up a static file server or exposing ports to services like localtunnel or ngrok.
Simple example:
```javascript
const path = require('path');
const ngrok = require('ngrok');
const { RemoteBrowserTarget } = require('happo.io');
module.exports = new Promise(async (resolve) => {
const url = await ngrok.connect(9090);
resolve({
apiKey: process.env.HAPPO_API_KEY,
apiSecret: process.env.HAPPO_API_SECRET,
targets: {
'chrome-desktop': new RemoteBrowserTarget('chrome', {
viewport: '1366x768',
}),
},
});
});
```
> Allow async user configs

- README.md
I added two lines in the README.md specifying which change URL to use in order to take advantage of Happo's GitHub integration.
> Update README's CHANGE_URL details

- bin/happo-ci
To make happo.io work better with legacy Happo (https://github.com/Galooshi/happo), I'm making the happo-ci script not depend on the `happo` binary. Legacy happo has the same binary name and it's causing collisions. We can invoke the `cli.js` file directly instead to work around this issue.
> Remove dependency on npm bin

- src/JSDOMDomProvider.js
- test/integrations/examples/Foo-react-happo.js
- test/integrations/react-test.js
This behavior is leading to unexpected and unwanted behavior where a
component calling cancelAnimationFrame on unmounting could lead to
issues in jsdom where the document is no longer defined.
> Stop no-op:ing cancelAnimationFrame

- bin/happo-ci
I spotted this stylistic issue after running this script
through shellcheck. More info:
https://github.com/koalaman/shellcheck/wiki/SC2236
> Use `-n` instead of `! -z` in bin/happo-ci

- src/domRunner.js
"Reading files" is really vague, so it is hard to know what happo is
doing here, and when it goes wrong it can be hard to know how to fix it.
> Make domRunner "Reading files" log more specific

- package.json
- src/browser/processor.js
- test/integrations/examples/Foo-react-happo.js
- test/integrations/react-test.js
Fixes #95.
Before, when an example renders to multiple DOM nodes, we would just
include one of them in the html snapshot. In many cases, this led to
empty/blank screenshots. Consider this html:
```html
<body>
<div id="happo-root"><div></div></div>
<div>
I'm in a portal!
</div>
</body>
```
With the old findRoot() implementation, only the inner div of
`#happo-root` would be included in the html snapshot. With the new
implementation, both elements would be included:
```html
<div id="happo-root"><div></div></div>
<div>
I'm in a portal!
</div>
</html>
This change is a little delicate as we have to be careful about
including too much in the html snapshot. For instance, if a React
component only renders to a portal, we don't want to include the empty
root:
this
```html
<body>
<div …
> Improve finding the root node

- src/JSDOMDomProvider.js
It looks like jsdom will add this detail property to the error object
for regular exceptions:
https://github.com/jsdom/jsdom/blob/3cb5ec40/lib/jsdom/living/helpers/runtime-script-errors.js#L63
However, for other types of errors, like XHR errors, this property does
not exist:
https://github.com/jsdom/jsdom/blob/699ed6b7/lib/jsdom/living/xhr-utils.js#L49-L59
Unfortunately, this code was written in a way that causes it to error
out like this:
```
/path/to/repo/node_modules/happo.io/build/JSDOMDomProvider.js:20
const len = e.detail.length;
^
TypeError: Cannot read property 'length' of undefined
at VirtualConsole.JSDOMDomProvider.virtualConsole.on.e (/path/to/repo/node_modules/happo.io/build/JSDOMDomProvider.js:20:28)
at emitOne (events.js:116:13)
at VirtualConsole.emit (events.js:211:7)
at …
```
> Fix bug in jsdomError handling when e.detail is undefined

- src/prepareAssetsPackage.js
I'm setting up happo for a project and am running into an error:
> entry name must be a non-empty string value
This is coming from the archiver package, and I think it can happen if
the `name` we pass to it is falsey. But it is hard for me to understand
where the problem might be in my setup, since this is all of the
information I have to work from.
In order to produce a more actionable error, I think we should throw
here.
> Throw if asset path cannot be resolved

- src/findAssetPaths.js
- test/findAssetPaths-test.js
- test/findCSSAssetPaths-test.js
When finding assets in the html snapshots, we were not properly handling
empty src attributes. This led to a cryptic error down the line:
Error: entry name must be a non-empty string value
We can simply ignore empty src to fix this. While I was trying to
reproduce the issue, I wrote a test case for css asset finding as well,
and I decided to keep it around even if it didn't cause any trouble.
> Ignore empty <img> src attributes

- package.json
- src/findAssetPaths.js
- test/findAssetPaths-test.js
We found a bug where srcsets with multiple URLs and mixed descriptors
would be parsed incorrectly, causing the first URL without a descriptor
to include a trailing comma. Instead of relying on this regex, I found
what appears to be a good package for parsing this string according to
the spec.
This is a port of this PR: https://github.com/Galooshi/happo/pull/229
> Replace srcset parsing regex with parse-srcset package

- package.json
- src/findAssetPaths.js
- test/findAssetPaths-test.js
(Note: this contains 2 commits, the first is part of https://github.com/happo/happo.io/pull/101, and the second is the commit specifically for this PR)
Fixes #100
I have a snapshot that renders the following element:
```html
<div class="background_3l6wgj-o_O-large_usp5di" style="background-image: url(19674e0d6b42a252d31d6290dc406e1b.png);" role="img" aria-label="image"></div>
```
When happo takes a screenshot of this element, the image is missing.
When I view the snapshot source, I see the network request for this
image 404.
I believe that when the assets package is prepared, it is looking at
global CSS files, snap payloads, and things added to the public folders.
https://github.com/happo/happo.io/blob/b4ceb19bec/src/domRunner.js#L90-L94
The snapPayloads.assetPaths are added to the assets …
> Find assets from inline styles

- .travis.yml
10 is currently in LTS and 12 will start LTS in October. It seems
like a good idea to run CI on these versions.
> Add Node 10 and 12 to Travis test matrix

- bin/happo-ci
The recent refactoring here leaves git checked out to PREVIOUS_SHA,
which is unexpected for any following commands that are run. To make
this more seamless, I think we should check out the CURRENT_SHA here so
that things are in a better state.
> Check out CURRENT_SHA after reporting on PREVIOUS_SHA

- bin/happo-ci
- src/commands/startJob.js
- src/executeCli.js
- test/happo-ci-test.js
This will contextualize the job a little on the happo.io side, and it
will make sure that a github status is posted as soon as the job starts.
> Send `link` and `message` with `start-job` command

- src/commands/startJob.js
I've been seeing the occasional error when running start-job that looks
like this:
> StatusCodeError: 503 - "upstream connect error or disconnect/reset
> before headers"
This has appeared about 3 times that I can tell over the past 2 days at
Airbnb. I think it is some intermittent problem, potentially in our
infrastructure, and we can probably just retry the API request and it
will probably just succeed. This will remove a small amount of pain for
our developers.
> Retry failed start-job up to 3 times

- src/findAssetPaths.js
- src/findCSSAssetPaths.js
- src/stripQueryString.js
- src/stripQueryStringAndHash.js
- test/findAssetPaths-test.js
- test/findCSSAssetPaths-test.js
Happo has some logic that looks for any local assets needed to render
the examples in a browser (e.g. images), and tries to bundle them up so
they can be available during screenshotting.
We've recently noticed a bug where some of our local images are failing
to load. When viewing source in the Happo UI, these images are 404ing,
and they do not exist in the assets zip file.
We noticed that these local images have some query strings added to
them. We believe that these query strings are causing these images to
not be bundled up with the other assets.
In this commit, I am hoping to make this better by stripping query
strings from the URLs. I started by trying to use node's URL built-in
parsing, but I found a couple of issues:
1. The `new URL()` API does not support relative URIs. There are …
> Strip query strings and hashes when finding assets

- src/RemoteBrowserTarget.js
- src/commands/compareReports.js
- src/commands/startJob.js
- src/uploadReport.js
We are seeing some intermittent 404 errors when making various requests
in our Happo CI jobs:
```
StatusCodeError: 404 - "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```
These 404s happen with a variety of requests, and the error message
appears to be generated by nginx, which Happo does not use. My suspicion
is that this is something else in our infrastructure that is being
flaky. While I investigate the root cause, I think making Happo a bit
more fault tolerant would help reduce some pain from our engineers when
stuff like this crops up.
Since we've added exponential backoff and jitter to the retry mechanism,
this should be relatively safe to do across …
> Retry most requests 5 times

- src/RemoteBrowserTarget.js
- test/RemoteBrowserTarget-test.js
The rendering options are used by happo workers to control certain type
of behavior. Right now the only supported option (currently under
development) is `prefersReducedMotion` (chrome only) but more might
come.
> Add `renderingOptions` to RemoteBrowserTarget

- README.md
This bit seemed to be injected in the middle of the
chunks documentation.
I also added some headings to make this structure
more obvious.
> Reorder chunks documentation a little

- src/RemoteBrowserTarget.js
- test/RemoteBrowserTarget-test.js
We've been making some changes on the happo.io server side to avoid
reading large payloads into memory. One of the places where we had to
process large json was when payloads were posted from
RemoteBrowserTarget. The server has been updated to allow data to be
sent via multipart/formdata.
A new requirement from this new feature is that the client sends along a
hash of the payload contents. This is used on the server to optimize
certain things. When we're sending a `pages` config, we need to
randomize the hash (this was previously done server-side).
> Send payloads as multipart/formdata

- bin/happo-ci
- test/happo-ci-test.js
The first time that Happo runs in CI, it currently runs `git checkout`
to check out the SHA. However, git should already be on that SHA since
it is the first run.
At Airbnb, I noticed that this step can take ~10 seconds, so skipping
over it when it is unnecessary should give us a little speed boost. It
is unclear to me exactly why this would take so long, so maybe all of
the time will just move over to the next git operation, but this seems
like a reasonable thing to do regardless.
> Skip git checkout when run-happo is in quick mode

- bin/happo-ci
- test/git-mock.js
- test/happo-ci-test.js
A recent commit (7780feb) made happo-ci skip doing a git checkout for
the current sha. This is good, as it makes things faster (a git checkout
can take some time in a large repo). But it made me aware of a flaw in
the logic around "QUICK". In most cases, CURRENT_SHA will be the same as
HEAD. But in some cases (as is the case when CI runs on a constructed
merge commit), CURRENT_SHA might actually be different from HEAD. In
this case we actually want to perform the git checkout.
By adjusting the "QUICK" logic to instead rev-parse the HEAD to see what
sha we're currently on and compare with the sha in question, we can keep
the speed-up from 7780feb yet still do the right thing when CURRENT_SHA
is not HEAD.
> Be smarter about checking out and npm installing

- src/Logger.js
- src/domRunner.js
- src/pageRunner.js
- src/remoteRunner.js
This is a little hacky, ideally we'd detach timing numbers from the
logger. It fixes logs like these:
- chrome-small ✅ (0.1ms)
- chrome-large ✅ (0.1ms)
Instead, you'll see real timing numbers:
- chrome-small ✅ (1234.7ms)
- chrome-large ✅ (7613.2ms)
> Fix incorrect timing numbers

- .eslintignore
- test/integrations/error-test.js
- test/integrations/examples/Foo-error-syntax-happo.js
We're tracking down a strange bug where the happo run fails silently
with an uncaught build error logged to the console. This is an attempt
to recreate.
> Add integration test to verify build errors are handled

- README.md
- package.json
- src/commands/compareReports.js
- src/compareSnapshots.js
- test/commands/compareReports-test.js
- test/compareSnapshots-test.js
- yarn.lock
This should better align the compareThreshold option with human
perception.
From https://github.com/happo/lcs-image-diff/pull/6
***
Our first iteration of measuring the difference of two colors used a
basic euclidean distance. However, this is not very well aligned
with how human vision works, so it produces disappointing results when
applied to real world diffs.
Looking for a better option, I found mapbox's pixelmatch package, which
describes itself as:
> The smallest, simplest and fastest JavaScript pixel-level image
> comparison library, originally created to compare screenshots in
> tests.
This sounds perfect for this application.
The pixelmatch package has functions that take two entire images, and
does a lot more than we actually need here, so instead of pulling it in
as a …
> Use new YIQ colorDelta for deep compare 

- package.json
- yarn.lock
While updating to happo.io v5, I ran into problems with this new version
of jsdom. I believe this issue is tracking one of these issues:
https://github.com/jsdom/jsdom/issues/2667
> Downgrade jsdom 15 back to 12

- README.md
- bin/happo-ci-circleci
- bin/happo-ci-travis
For a default branch build, the happo-ci-travis script would run a
comparison between the current commit and the commit that travis last
knew about (that it had built). This led to failing builds for people
on some master/default branch builds because there would be a red happo
status (needs review). We can make this better by detecting when there
is a master/default branch build and only run a single report for that
commit.
Unfortunately, there's no way in Travis to know what the default branch,
so we'll have to default on `master` and then let people pass in a
different base branch using BASE_BRANCH if master isn't the one. This is
similar to what the happo-ci-circleci script does (although it depends
on it even more by looking up the PREVIOUS_SHA using a git-rev-parse).
> Improve master branch runs for happo-ci-travis

- .babelrc
We haven't supported Node 6 in a while.
> Target node 8 in .babelrc

- src/cli.js
We're trying to track down an issue where a build with a lot of diffs
(~2000) being deep-compared is leading to the process exiting (1)
without having had time to complete all the stdout/stderr printing.
Since writing to stdout/err is asynchronous in nature, we believe that
the call to process.exit in our unhandledRejections handler is masking
the error being logged right before the exit. By instead throwing an
error we get the same behavior (exit 1) but we allow node to finish up
what it needs to do first.
> Throw instead of exiting on unhandledRejection

- src/commands/compareReports.js
- test/commands/compareReports-test.js
We are running into an issue where our CI job fails when the number
of diffs to compare is really long. The error messages are either
never output, or confusing ("echo: write error: Resource temporarily
unavailable") so we don't have any strong leads on what exactly
could be causing it, and we have yet been able to reproduce it
locally.
One theory we have is that we are logging too much too quickly in
node which is causing the command to fail. A lot of this logging is
pretty unnecessary anyway so we are hoping to narrow down the
problem by logging less.
> Log less in compareReports

- README.md
- package.json
- src/RemoteBrowserTarget.js
- src/commands/compareReports.js
- src/commands/run.js
- src/domRunner.js
- src/executeCli.js
- src/pageRunner.js
- src/remoteRunner.js
- test/RemoteBrowserTarget-test.js
The idea of an async report is that the happo command can finish as soon
as the snap-requests have been initialized. The server will then
construct the report once all snap-requests are done.
So far, only RemoteBrowserTarget is aware of async reports, but going
forward the `happo run` command will know about it too (in some way).
> Add support for async reports

- src/domRunner.js
- test/integrations/error-test.js
- test/integrations/examples/Foo-error-empty-happo.js
At Airbnb, we have a pretty complex setup where we have a bunch of
independent projects that are using Happo, and they pull from a shared
Happo configuration. Each component can decide which viewport sizes it
should be rendered in, which maps to a set of Happo targets. We have a
bunch of targets that map to the breakpoints we use in production. Most
components only use a couple of targets, and no projects currently use
all of the targets at once.
Currently, Happo will throw an error if one of the targets does not have
any tests for it. As a workaround, we generate stub tests for each
target. However, that comes with a bunch of overhead that we would be
able to avoid if Happo didn't have this restriction.
I think that throwing and failing the job might help some people
discover that they …
> Avoid throwing when there are no examples found

- src/createWebpackBundle.js
If you're setting up a "full-page" integration, you shouldn't have to
install webpack. By moving webpack into a dynamic import, we can avoid
having it as a runtime dependency when you're not using the Happo
Examples integration.
https://docs.happo.io/docs/full-page
https://docs.happo.io/docs/examples
> Loosen the dependency on webpack

- src/domRunner.js
- test/integrations/MockTarget.js
- test/integrations/examples/Generated-react-happo.js
- test/integrations/react-test.js
We've been seeing some issues with our Happo jobs in CI. Occasionally,
they exit with status code 137, which seems to be how Kubernetes handles
processes that have exhausted all of the available memory. This always
seems to happen after "Generating screenshots in 6 targets..." is
logged. We are using the domRunner with the JSDOM prerendering.
I suspect that the call to executeTargetWithPrerender, which will
initialize a JSDOM environment and then execute our bundle in it, uses a
lot of memory. Since we are doing this 6 times in parallel, one for each
of the targets we have configured, this ends up using up too much
memory.
To resolve this, I think we need to dial back the parallelization here.
Since these tasks are not using separate threads or anything like that,
they are all sharing the …
> Execute targets serially in domRunner generateScreenshots

- src/getComponentNameFromFileName.js
- test/getComponentNameFromFileName-test.js
This came up while debugging long component names in a customer's
report. It turns out they named their files e.g. Component.happo.tsx,
and we weren't able to parse out the component name from that file name.
> Allow Happo Example files to end with *.happo.suffix

- src/authForFetch.js
- src/commands/compareReports.js
- src/compareSnapshots.js
- src/fetchPng.js
- src/fetchPngInMemory.js
- test/commands/compareReports-test.js
- test/compareSnapshots-test.js
- test/fetchPng-test.js
When fetching images to deep-compare, there's a chance they aren't
publicly available. If we're talking to a happo.io server, we can send
along the JWT token which will authenticate our requests towards the
happo API.
> Send API credentials when deep-comparing

- bin/happo-ci-github-actions
If you set up github actions to run on push events, no comparisons were
made. This was because we resolved to PREVIOUS_SHA to the same sha as
the CURRENT_SHA.
It seems like this was a silly mistake made in the initial commit
(c998d6d4). It could be that we did want the shas to be the same for
master push builds, but I can't find anything in the git commit message
about this, so I'm assuming it's a mistake.
I used this link to see what properties are available for the push
event:
https://developer.github.com/webhooks/event-payloads/
> Fix resolving PREVIOUS_SHA for github actions push builds

- src/findAssetPaths.js
- test/findAssetPaths-test.js
We received a report of a confusing Happo report. Looking at the source
of the "after" version, the problematic part seemed to be related to a
`<picture>` element with nested `<source>` elements that used `srcset`.
After downloading the assets zip file for this report, we noticed that
the assets for these images were not included. I suspected that this was
related to our asset finding code, which we confirmed by pushing up a
change that included regular `<img>` tags with the same assets, which
ended up fixing the confusing report.
To fix this bug, we can include these elements in our srcset extraction
query selector. Since `<source>` is used for `<picture>`, `<video>`, and
`<audio>`, I scoped the selector to source elements that descend from
picture elements to avoid also grabbing audio …
> Find asset paths in picture source srcsets

- src/cli.js
I am attempting to disable sourcemaps in our Happo installation to
improve performance and scalability. This seems to work okay for most of
our projects, but in a couple, I end up with jobs that fail with stack
traces like this:
```
Error: ENOENT: no such file or directory, open '/path/to/repo/build/react-router.js.map'
at Object.openSync (fs.js:458:3)
at Object.readFileSync (fs.js:360:35)
at Array.retrieveFile (/path/to/repo/node_modules/happo.io/build/cli.js:32:25)
at /path/to/repo/node_modules/source-map-support/source-map-support.js:65:24
at Array.<anonymous> (/path/to/repo/node_modules/source-map-support/source-map-support.js:179:21)
at /path/to/repo/node_modules/source-map-support/source-map-support.js:65:24
at mapSourcePosition …
```
> Avoid erroring when `devtool: false` is used

- .travis.yml
- package.json
- src/createWebpackBundle.js
- test/integrations/react-test.js
- yarn.lock
Webpack version 5 was recently released and it's time we make sure to be
compatible.
At first look, I was going to drop support for webpack 3, but then I
decided to avoid that for now to prevent having to make (another) major
version bump (I just bumped to v6).
The transition was mostly smooth except for two things:
- some dependency is relying on `path` for something. Webpack 4 would
automatically shim built-ins from Node, but now it's erroring. I added
a no-op `fallback` for `path` and things seem to be working.
- The react-test had a webpack config that was partly incompatible with
webpack 5. I had to mess around with publicPath for file-loader
(including upgrading file-loader) to get things in a stable format.
> Support webpack 5

- src/Logger.js
- src/commands/run.js
- src/domRunner.js
- src/pageRunner.js
- src/remoteRunner.js
- test/Logger-test.js
At Airbnb, we are running Happo on a bunch of different projects in
parallel. Since the logs end up getting all mixed together, it is hard
to tell what is actually happening. I'm hoping we can make this better
by including the project name in the log lines if it exists.
I'm not totally in love with this approach, but anything cleaner would
require a deeper refactor of the way logging works in this project, and
I'm not really interested in doing that right now.
> Include project name in logs

- src/commands/compareReports.js
- src/executeCli.js
- test/commands/compareReports-test.js
This new option can be used with the compare call to send emails to
people when a comparison is ready.
> Add `notify` option

- package.json
- src/domRunner.js
- src/prepareAssetsPackage.js
- test/integrations/react-test.js
- test/prepareAssetsPackage-test.js
To reduce traffic towards s3 and avoid having to be throttled, we can
attempt to reuse asset packages between runs. This is already done for
static runs (e.g. storybook) but it's a little trickier to reuse things
between prerendered runs because assets might differ based on the size
of the viewport. Still, we can use a cache of known asset packages and
avoid the upload if the package is known.
I plan on pairing this change with an update to happo servers as well,
where we avoid the s3 upload if we come across a package that we've seen
and uploaded before. The cache used here is simply local to the cli
invocation, but a cache on happo servers can live longer than that.
> Upload assets for prerender runs separately

- bin/happo-ci
At Airbnb, we are using Happo with orchestration. When we originally
started using this, we had a race condition between the orchestration
API call and when the projects would start running Happo. In this
scenario, we needed to always run the start-job command, which ensures
that a job is created for these, and if orchestration is used then it is
smart enough to combine the separate start-job calls into a single
orchestrated job.
More recently, we've observed some database contention partly due to our
scale. In my investigation, I realized that we have since resolved this
race condition and now have a guarantee that the orchestrate endpoint
will be called before Happo is run on any project in the PR. This means
that we can save a bunch of work by skipping this start-job command.
To make …
> Add HAPPO_SKIP_START_JOB to happo-ci script

- .npmignore
When I published the latest version, I noticed that most of the package
size comes from a few PNG files that aren't really needed by consumers.
```
npm notice 16.6kB  happo-accept.png
npm notice 22.0kB  happo-dot-io-logo.png
npm notice 168.0kB happo-report.png
npm notice 49.9kB  happo-status-accepted.png
npm notice 150.8kB happo-status-diffs.png
```
Ignoring these will help keep the package size nice and small.
> Add *.png to .npmignore

- package.json
- src/commands/dev.js
- src/commands/run.js
Node 10 added a recursive option that I think we can use here instead of
bringing in this dependency.
> Replace mkdirp with fs.mkdir recursive

- bin/happo-ci
- package.json
- test/happo-ci-test.js
When the HAPPO_IS_ASYNC environment variable is set to "true", the
happo-ci script won't check out the previous commit and create a report.
Instead, we rely on that report (or a fallback) to already exist.
Async runs are faster and frees up valuable CI runtime since they don't
wait for the screenshots to be ready before exiting.
This is a breaking change for anyone using the happo-ci script directly,
the happo-ci-travis script, and the happo-ci-circleci script. The
happo-ci-github-actions script was already using async mode (it was
added later on and had async from the start).
> Make async mode the default in CI

- package.json
- src/DEFAULTS.js
- src/createWebpackBundle.js
- src/domRunner.js
As I'm debugging an issue with Next.js@v11, I'm noticing that it's using a custom built webpack. To make it possible to use the custom webpack instance, I'm adding support for a new `webpack` option in .happo.js.
> Add ability to inject custom webpack

- src/commands/run.js
The truthiness if staticPlugin is checked to determine if Happo should
use the remoteRunner, but since this is always assigned to an object
now, the logic was broken and Happo would never end up using the
domRunner. I believe we can fix this by being a little more careful
about how we assign the staticPlugin variable.
> Fix staticPlugin check

- package.json
- src/Logger.js
- test/Logger-test.js
- yarn.lock
In https://github.com/happo/happo.io/pull/189 we made some improvments
to make the logs clearer when running Happo on multiple projects in
parallel. After landing this change, I noticed that since we leave
lines open with start() to be completed by success() or fail(), we
still get some logs that are a bit weird or confusing.
To make this better, I am changing start() to always log a newline,
and then teaching success() and fail() to include the start message if
it exists.
Now that the logger is getting a bit more complex in its output, I
decided that it would be helpful to have full examples of what it is
logging in the test suite, and Jest inline snapshots work well for
this. In order for the timings to be stable, we need to mock out the
timer, and Jest mock timers will mock out Date, …
> Log start() and success()/fail() on separate lines

- package.json
- src/DEFAULTS.js
- src/JSDOMDomProvider.js
- src/mergeJSDOMOptions.js
- test/mergeJSDOMOptions-test.js
Hello! In our setup, I need to provide a `beforeParse` jsDOM option to provide a missing browser API. However, this function would override the function that is declared by default in `JSDOMProvider`. 
In this PR:
- I create a function `mergeJsdomOptions` which is almost like an `Object.assign`, but it doesn't override functions. Instead, it calls both provided functions, first default, then the one configured by the user.
- I add a test for that function
- I add `jsdomOptions` to the `DEFAULTS` file because it was throwing a warning, even though it processed `jsdomOptions`
- I bump a minor version because I don't think that my PR is fixing a bug
> feat: add a `mergeJSDOMOptions` function

- bin/happo-ci
I've had a report from a customer where the happo-ci flow is running
in async (HAPPO_IS_ASYNC=true) mode but the inner commands (happo run,
happo compare) are triggered in non-async mode. I think this is because
the HAPPO_IS_ASYNC variable isn't exported from the parent script.
Granted, the export isn't needed in most shell environments (my tests
show that it's enough to set it in the parent in bash and sh on Mac).
Exporting it makes the dependency clearer though, and is likely to fix
issues in certain shell environments.
> Export HAPPO_IS_ASYNC in happo-ci

- src/createDynamicEntryPoint.js
I'm chasing a bug in windows environments where this error shows up:
Module not found: Error: Can't resolve C:some-folderreact-domindex.js
I think this is because requireRelative.resolve doesn't work on Windows.
The require-relative module isn't really needed here (and I question if
we need it elsewhere as well). The commit that added it was
6af271e15e and it doesn't mention require-relative as a hard
requirement. From what I can tell, we might as well use
require.resolve().
> Fix requiring react-dom in entry point on windows

- bin/happo-ci-azure-pipelines
It's not uncommon that you want to override PREVIOUS_SHA. Other scripts
allow this, I just didn't think to do it when I worked on this
previously.
> Allow env variable override in happo-ci-azure-pipelines

- .happo.js
- src/domRunner.js
- src/ensureTarget.js
- src/pageRunner.js
- src/remoteRunner.js
When running happo via npx, there's little need to install happo
locally. But since the .happo.js config needs to import
RemoteBrowserTarget to work, npx run was hard to do. We can fix this by
dynamically creating the RemoteBrowserTarget instances when we need
them (if they aren't already real targets). The `browserType` option
will specify what browser to use.
> Allow .happo.js config to be free from happo.io import

- bin/happo-ci-azure-pipelines
I noticed these links were 404ing. Turns out there's a missing
"/pullrequest/" part here.
> Fix PR link set by happo-ci-azure-pipelines

- src/RemoteBrowserTarget.js
- src/commands/run.js
- test/RemoteBrowserTarget-test.js
Add support for extends in pages config items
This is a new feature for people on the full-page integration. Instead
of providing urls for all pages, they can provide `extends: <sha>` to
have the snapshot injected from a different report.
https://docs.happo.io/docs/full-page
> Add support for extends in pages config items

- src/DEFAULTS.js
Fix `Unknown config key used in .happo.js: "afterSyncComparison"` warning when passed `afterSyncComparison` configuration
> fix(comparison)-config-key-validation

- package.json
- src/makeRequest.js
- test/makeRequest-test.js
- yarn.lock
With the change from request-promise-native to node-fetch, we changed request timeouts (they're now shorter). Some test suites are running into timeouts from the asset upload fetch call. By increasing the timeout we hope to unbreak these test suites.
> Fix fetch timeouts

- src/RemoteBrowserTarget.js
I'm doing this so that it's easier to grep logs when I need to do debugging.
> Add identifiable query param to snap-requests POST

- package.json
- src/JSDOMDomProvider.js
- test/integrations/error-test.js
I'm trying to fix a silent crash/exit coming from loading the bundle. Before I get to the juicy parts, I want to make sure we don't stall forever waiting for onBundleReady.
> Add timeout waiting for `onBundleReady`

- src/createWebpackBundle.js
From the report:
webpack calls this callback without actually waiting for the bundle to be written disk, and jsdom winds up reading a partially-written file. adding a setTimeout in there “fixes” it.
> Give webpack time to write bundle file before callback

- src/makeRequest.js
Before, only ones that failed because of a non-2xx exit code would have the total time. After this change, even ones that fail on the network level (such as `socket hang up`) will get logged.
> Add request time to all failures in makeRequest.js

- src/browser/processor.js
- test/integrations/react-test.js
This will cause it to be excluded from the rectangle calculation when used with prerender:false.
When migrating one of my projects from prerender:true to prerender:false I noticed that there was an extra rectangle around smaller examples. Turns out the root element was causing this. In a prerender:true world, we grab the innerHTML of this root node so it isn't present in rendering on Happo workers.
> Add data-happo-ignore to root element

- src/browser/processor.js
- src/browser/remoteRenderer.js
- src/browser/validateAndFilterExamples.js
- test/browser/validateAndFilterExamples-test.js
Also, make sure that chunk information is honored.
happoProcessor.init has been deprecated for a while, but remote rendered builds have still used it. I'm adding the happo.init function instead and at the same time making sure that we honor chunk information.
> Introduce happo.init for remote render

- src/executeCli.js
- test/cli-test.js
- test/commands/compareReports-test.js
This arg was treated as a flag as opposed to an argument with a value. Fixed that and added some tests around that. Also made it clearer that fallback shas can be passed as a newline or space separated list as well.
> Fix passing in --fallbackShas

- src/domRunner.js
- src/remoteRunner.js
- src/uploadAssets.js
Sometimes we get network errors when making requests. Most endpoints are retried but the assets-data check is only performed once. When it fails with a non-404 response, the execution halts. We can improve this by instead assuming the assets are not there and continue as if we had a
404. I've added a warning log just to make sure we surface this issue.
> Warn instead of failing when asset check fails

- bin/happo-ci
- test/cli-mock.js
- test/happo-ci-test.js
This PR adds some logs to the happo-ci script, to help with debugging.
> More logging

- package.json
In https://github.com/happo/happo.io/pull/276 we replaced the jsonwebtoken package with jose, which uses syntax that does not work on node 14 or earlier. I think it might be worthwhile to make this compatibility a little more explicit in our engines field.
> Change package.json engines field from node 12 to 16

- bin/happo-ci
- test/cli-mock.js
- test/happo-ci-test.js
I made a mistake when adding this call earlier. Unfortunately tests didn't catch it because they are using a mock.
> Fix invalid version command in happo-ci

- .github/workflows/test.yml
This resolves some warnings related to the node version these actions are using.
> Update actions/checkout and actions/setup-node from v2 to v4

- src/loadUserConfig.js
- test/loadUserConfig-test.js
I was debugging an error recently where I saw the following logged:
> No `apiKey` or `apiSecret` found in config. Falling back to
> pull-request authentication.
I believe in this particular case that only one of these was missing and I thought it might be nice if this error message was a little more specifically helpful.
> Improve error message for missing apiKey and apiSecret

- .gitignore
- .npmignore
- package.json
- src/createStaticPackage.js
- src/prepareAssetsPackage.js
- src/remoteRunner.js
- test/createStaticPackage-test.js
- yarn.lock
I noticed that the Jest test that verifies the stability of these hashes
was flaking and determined that the output was, in fact, not
determinstic.
I beleve there are two possibile sources of nondeterminism in these
zips:
1. The order of files being globbed may be nondeterministic
2. Concurrency in archiver's stat queue causes nondeterminism
In the end, I believe most of the problem is likely caused by 2, but I
figured that we might as well address the theoretical glob order at the
same time.
More info:
https://github.com/archiverjs/node-archiver/issues/383#issuecomment-2252938075
> Make archives deterministic

- test/createStaticPackage-test.js
Originally, we were just testing to see that the hash was the same twice in a row. This test often passed when our hashes were not deterministic. I want to make this test more likely to fail when hashes are not deterministic, so I am running it 20 times. This should help us ensure that these hashes remain deterministic.
> Improve determinstic hashes test

- .github/workflows/test.yml
I believe that this will enable us to change the default branch in this repo from master to main.
Just before this merges we will update the default branch in this repo from master to main.
> Change master to main for github workflows

- bin/happo-ci-circleci
- bin/happo-ci-travis
- test/github_pull_request_event.json
- test/github_push_event.json
In cases where we can't figure out a baseline commit in our CI scripts, we default to `origin/master`. This was the usual default branch name back in the days, but it has since changed to `origin/main`. I'm making the switch to "main" now.
This is a breaking change but one that is easy to make non-breaking if you use a BASE_BRANCH=origin/master environment variable.
> Default to branch named "main"

- .github/workflows/test.yml
This improves the readability of the test output in CI.
> Run Jest with `--colors` in CI

- src/loadUserConfig.js
- test/loadUserConfig-test.js
Fixes https://github.com/happo/happo-e2e/issues/50
Note that this PR doesn't change how the file itself is loaded to completely settle ESM compat, but it at least makes the CLI work properly when used in conjunction with `NODE_OPTIONS='--experimental-require-module'`
> fix: handle ESM-style config file

- .github/workflows/test.yml
- package.json
- src/makeRequest.js
Just a small refactor to help clean up this code a bit.
`AbortSignal.timeout` is available as of Node 17.3.0, so I am also updating the engines field and removing the Node 16 tests.
> Use AbortSignal.timeout instead of AbortController in makeRequest

- src/makeRequest.js
- test/makeRequest-test.js
The makeRequest function accepts some options that default to undefined when they are not specified. These are then passed into async-retry, which eventually gets merged into the default options in a loop like this:
```js
for (var key in options) {
opts[key] = options[key];
}
```
https://github.com/tim-kos/node-retry/blob/11efd6e4/lib/retry.js#L17-L26
This means that when the options are not specified, they end up overriding the reasonable defaults, which was unintentional.
The result is that since we don't specify these options most of the time, most of the requests will be retried immediately instead of waiting a little bit.
To fix this, we need to construct the options a little more carefully.
I wanted to test this using jest fake timers, but when I did that it caused the tests to …
> Avoid passing undefined through to async-retry, remove maxTries option

- src/createStaticPackage.js
- src/prepareAssetsPackage.js
- src/remoteRunner.js
It seems that by default Archiver uses zlib level 1, which prioritizes compression speed over compression ratio. By default, zlib uses level 6, which is a nice balance between compression speed and compression ratio. In my testing, level 6 does indeed seem to be a sweet spot, and seems to make my test cases about 14% smaller without sacrificing much performance.
Since these zips are immediately uploaded, stored, and downloaded again somewhere else, I am hopeful that this 14% size difference will more than make up for slightly slower compression speeds.
> Use zlib level 6 when making zip files

- src/createStaticPackage.js
- src/deterministicArchive.js
- src/domRunner.js
- src/prepareAssetsPackage.js
- src/remoteRunner.js
- test/createStaticPackage-test.js
- test/deterministicArchive-test.js
- test/integrations/react-test.js
- test/prepareAssetsPackage-test.js
We had three places that were interfacing with the archiver package, and they all need to do basically the same thing--create a deterministic zip file. If the zip file is nondeterministic, then downstream problems with caching will arise. Since creating a deterministic zip requires some special handling, I decided that it would be best to refactor this code to all run through the same function that guarantees a deterministic output.
While working on this I noticed that the remoteRunner was using archiver's directory function, which I believe can by nondeterministic, so this should help to stabilize those zip files.
> Refactor archiving to go through single determinstic function

- package.json
- src/findCSSAssetPaths.js
- yarn.lock
We only use this in Node, and it is available since Node 12. Since we only support Node 18+, it is safe to remove the dependency.
> Remove string.prototype.matchall dependency

- .npmignore
I checked this with:
```sh
npm pack --dry-run
```
We don't need to publish any of these files.
> Add some files to npmignore

- .github/workflows/test.yml
I added this option when I set up linting in CI, and we might as well use it in our Jest tests to make them faster.
> Use yarn cache for Jest tests in CI

- package.json
- src/commands/dev.js
- src/commands/run.js
- yarn.lock
We can avoid rimraf in our JS code pretty easily since Node 16 added the recursive option to rm.
> Update rimraf v3 to v6 and use node fs.rm in commands

- package.json
- src/makeRequest.js
- yarn.lock
The main breaking change is in v6, which changes the signature of the constructor.
https://github.com/TooTallNate/proxy-agents/blob/main/packages/https-proxy-agent/CHANGELOG.md#600
Looking at our usage, I don't think we need to do anything special to adjust for this.
> Update https-proxy-agent v5 to v7

- package.json
We only use this to clear out the build directory locally.
> Move rimraf to dev dependencies

- src/findTestFiles.js
After updating the glob package and trying out happo.io@v12.0.0-beta.1, I noticed that there were some diffs that I hadn't expected. After some investigation I noticed that the order of some of the test files in the generated happo-entry.js file changed, which I think may have been triggered by the changes in findTestFiles and the glob package update.
I am hoping to stabilize this by sorting the files.
> Sort files in findTestFiles

- package.json
- src/domRunner.js
- src/uploadAssets.js
- test/integrations/react-test.js
- yarn.lock
Add way to opt in to uploading assets with signed URLs
This will allow folks to opt in to using signed URLs by setting the
HAPPO_SIGNED_URL env var.
This requires a separate change to land on the server side before it can
be used.
To support this change, I ended up doing some bigger refactoring to the
react integration test. This change should make the test a lot more
realistic, because it now avoids mocking the makeRequest method in favor
of spinning up a server that responds with mock responses.
> Add way to opt in to uploading assets with signed URLs

- src/uploadAssets.js
- test/integrations/react-test.js
We need to use the correct API endpoint here.
> Use correct URL for finalizing signed URL uploads

- package.json
- yarn.lock
The only change listed in the v11 changelog is dropping support for node before v20. We want to support node v18 right now, so I am downgrading this back to v10.
https://github.com/isaacs/node-glob/blob/main/changelog.md#110
> Dowgrade glob v11 to v10

- .github/workflows/test.yml
- src/deterministicArchive.js
The `path` and `parentPath` properties of a Dirent object isn't available until 18.17 and 18.20 respectively. To make our package compatible again with older Node versions, I'm switching out `fs.readdir` for `glob`.
> Fix recursing to find files in Node <18.17

- src/deterministicArchive.js
We don't use these types for anything yet, so this is just for our own reference purposes.
This argument is passed through to archiver, which can accept these types.
> Add Buffer | ReadableStream to determinsticArchive arg type

- src/executeCli.js
We recently made some adjstuments that allow for this to work with async comparisons made by Playwright and Cypress. More info:
https://github.com/happo/happo-e2e/issues/71
I thin this means that we can also modify this code so it will work with async comparisons produced by this package.
While I was in here I also refactored these commands to set `process.exitCode` instead of calling `process.exit()` which can interrupt in-flight asynchronous work including writing to stdout/stderr. Since these are all in the top-level commands, I think returning normally will have the same result for the end user as `process.exit()` would have.
> Allow HAPPO_GITHUB_USER_CREDENTIALS to work with async comparisons

- src/deterministicArchive.js
- test/deterministicArchive-test.js
I found an issue with happo-cypress and inlined canvas images. Basically, the canvas element is converted to an image and inserted into the page, plus added to the asset package for the happo-cypress run. In old versions of the asset packages, the inlined canvas image would be kept in a `.happo-tmp/inlined/<hash>.png` file. In recent versions, the file is instead stored directly in the root of the asset package, `./<hash>.png`.
In happo-e2e, this commit introduce the bug to happo-cypress: https://github.com/happo/happo-e2e/commit/1cfe6ffbcb88ca638728918226dfbb632cc97866 (Use deterministicArchive.js from main happo.io library)
By keeping the directory structure, these entries will be stored in the right folder, so that the image elements will reference the right thing:
`<img …
> Keep dir structure for single files in deterministicArchive

- package.json
- yarn.lock
This package relies on jsdom@16.7.0, which was released in August, 2021. This version of jsdom relies on several deprecated packages, including:
- abab
- domexception
- w3c-hr-time
The latest version is v26.0.0, which was released January 9, 2025.
Closes #336
> Update jsdom v16 to v26

- src/executeCli.js
- src/postGithubComment.js
- test/postGithubComment-test.js
This is on a request from a customer. They are using comment posting and noticed that the list of comments grow quite long on a PR, especially when you are pushing a lot of changes to it. We can make this better by removing all old comments before posting our new one.
To make sure that only Happo comments are removed I'm adding a marker at the top of each comment (html comment) that we will use to make sure we only remove relevant comments.
This new behavior is opt-in and is only active when HAPPO_DELETE_OLD_COMMENTS="true"
> Delete old comments as part of posting new one

- bin/happo-ci
We noticed that this env var was not being exported, so it was not available to the happo compare script. This means that slower and more expensive database lookups need to happen since the list of fallback SHAs from git are not available to determine the baseline report SHAs.
> Export HAPPO_FALLBACK_SHAS from happo-ci

- src/createStaticPackage.js
- test/integrations/static-files/iframe.html
This file is used for Happo Examples with `prerender: false`. To make this document less likely to violate accessibility guidelines, I'm adding a lang attribute and a title element.
> Add lang="en" attribute to html element in iframe.html

- test/makeRequest-test.js
This reduces the indirection in this test a bit which makes it easier to understand.
> Remove subject pattern from makeRequest test

- src/constructReport.js
I'm working on a change to include axe results in Happo reports. This information needs to be passed along with the report in order to get Happo to use them.
> Include `axeResults` in constructed reports

- bin/happo-ci-github-actions
I've noticed that we often end up using the wrong report for comparisons
on GitHub actions. I think this is because the event JSON gives us
`pull_request.base.sha` as the tip of the base branch and not the merge
base SHA.
To make this work better, I think we want to use `git merge-base`. This
is similar to what we do in the CircleCI integration.
> Use git to determine previous SHA in GitHub actions

- .github/dependabot.yml
This package is published as part of Jest updates, so we want it grouped that way in our PRs. I am also adding the @jest namespace since I know Jest has packages published there as well.
> Tell dependabot to group babel-jest with jest updates
