happo/happo.io

bin/happo-ci
@trotzig Here are the two changes we talked about. They worked well on my machine but since testing them required editing files in `node_modules/` I'd really appreciate if you could try them out on your machine as well!
=> Improve happo-ci

package.json, src/createWebpackBundle.js
This PR attempts to fix issues with webpack compilation for those on babel 7.
=> Script missing

bin/happo-ci, src/createDynamicEntryPoint.js, test/integrations/examples/Foo-react-happo.js, test/integrations/react-test.js, test/integrations/reactSetup.js
I ended up bundling two changes here: 
- force checkout (overwriting local file changes on git checkout)
- allow custom `window.happoRender` `window.happoCleanup` functions defined in `setupScript`
=> Force checkout

bin/happo-ci, bin/happo-ci-circleci, bin/happo-ci-travis, package.json
A few goals here: 
- Make it easier to integrate with CircleCI and Travis (and others)
- Make things a little more robust (expanding shas, checking to make sure commits exist, etc)
=> Improve happo scripts

package.json, src/RemoteBrowserTarget.js, src/makeRequest.js, test/RemoteBrowserTarget-test.js
To mitigate users running into payload size limits, we are exploring options that will bring down the payload sizes in this PR:
- split up into multiple chunks
- add gzip compression
=> Smaller payloads

src/makeRequest.js
This will help us understand if it is trying to make a GET or a POST
request, which will make debugging a bit easier.
=> Add method to makeRequest failure log

.travis.yml, README.md, bin/happo-ci, test/git-mock.js, test/happo-ci-test.js
This is a follow-up to https://github.com/happo/happo.io/pull/105
=> Lencioni patch 4

README.md
I also reworded the sentence slightly to improve clarity.
=> Fix typo in compareThreshold documentation

src/makeRequest.js
When retrying requests, we want to spread out the work that clients are
doing so that they reduce the contention on the service which should
make the overall system more responsive and healthy, particularly when
there are many requests being retried at the same time.
The general way to do this is by adding exponential backoff with jitter.
More information can be found in this blog post from the AWS folks:
https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
=> Add exponential backoff with full jitter to makeRequest

README.md
Giving people more options that might be helpful.
=> Add link to mockdate

README.md
Thanks to @dangodev at Manifold for helping me find the right variables
to use when building Happo using GitHub Actions.
=> Add info about GitHub Actions to README

.travis.yml, src/Logger.js, test/Logger-test.js
I think this will make it a little easier to see where time is spent
during Happo runs.
=> Add timings to Logger

src/executeCli.js
=> feat(cli): warn appropriately if an unknown command was passed in

src/commands/compareReports.js
We've been running into some issues where this function causes jobs
to fail because we run out of file descriptors. We believe we've
already solved this by logging less in 44637b04c9837, but out of an
abundance of caution, we want to add some batching for the remaining
logs here since the added complexity is low.
=> Batch logs in compareReports

.eslintrc.js, package.json, src/browser/processor.js, src/createDynamicEntryPoint.js, src/renderWrapper.js, test/integrations/error-test.js, test/integrations/examples/Foo-error-throws-on-render-happo.js
It's been hard to understand when and where an error has happened in case a React component throws. This PR aims at improving some error handling for React.
=> Improve error handling when React component throws

src/remoteRunner.js, test/integrations/static-test.js
This is similar to a7ffd1d, but for static packages generated by plugins
(like happo-plugin-storybook). Instead of sending the static package in
the main payload, we can upload it separately and reuse in all
snap-requests.
=> Upload plugin static packages separate from main payload

.travis.yml
This will help ensure that this package is working okay on these newer
versions of node.
=> Add node 14 and 16 to test matrix

scripts/testPostGithubComment.js, src/postGithubComment.js, test/postGithubComment-test.js
This was broken since our switch to node-fetch.
=> Fix posting status as comment to github PR

.github/workflows/test.yml, .gitignore, package.json, src/cli.js, src/index.js, yarn.lock
If we move to Node 14, we no longer have to add the babel polyfill.
https://node.green/
=> Remove babel polyfill

.github/workflows/test.yml, package.json, yarn.lock
=> Allow babel-loader@9

src/domRunner.js
I had added this in our debugging session this morning but figured it would be good to contribute as well!
@trotzig
=> Include project name in css & snippets file paths

src/makeRequest.js
I'm adding the time it took to make the request so that we can debug things more easily. Also, make sure to log the error from each retry so that errors aren't lost.
=> Log more when makeRequest fails

src/domRunner.js
In 0be3322, we switched to serial execution of all targets. This helped make things more stable and prevented contention on cpu and memory on CI machines. In dd4d534103, I reverted some of this behavior to make sure that we make the POST to snap-requests as soon as possible. I'm pretty sure this has a bad effect on performance when there are large payloads and targets. All POST requests are made slower which makes us run into timeout issues and sockets being hung up.
To improve things, we can await the POST before we move to the next target. We need to be careful and only do this in the async case, because sync execution will poll and wait for results before continuing to the next target.
=> Let snap-request POST finish before moving to next target

package.json, yarn.lock
We only use this in our tests, and I am updating to help keep things fresh.
=> Update http-server from v0.12 to v14

.github/workflows/test.yml
I'm surprised we weren't already doing this!
=> Run ESLint in CI

src/makeRequest.js
This can help troubleshooting efforts.
=> Log the time when retrying failed requests

src/uploadAssets.js, test/integrations/react-test.js
While rolling this out we observed that these PUT requests to S3 signed URLs can occasionally result in 5xx errors. To make this smoother, I am adding some retries.
=> Retry S3 signed URL PUT requests

src/postGithubComment.js, test/postGithubComment-test.js
This is the GitHub Enterprise scenario where instead of a status post we post a comment to the PR with a status image and a link to the Happo comparison report.
Our legacy support will use a personal access token and basic auth to post a comment. This works but it makes it weird because the comment looks like it's coming from a user. And if that user leaves the company they have to update the credentials etc.
When using GitHub actions, we are fed with a secrets.GITHUB_TOKEN that has the right permissions to post a comment to the PR. It is short-lived which means it is more secure. We can allow people to pass it in using HAPPO_GITHUB_TOKEN and then use it instead of HAPPO_GITHUB_USER_CREDENTIALS.
=> Add support for HAPPO_GITHUB_TOKEN when posting comment
